### ISSUE TITLE
Getting Error 500

### ISSUE THREAD

**Issue by ghost** [clonemeagain/osticket-not-yours-plugin#2]
After enabling the plugin, I get an error 500 on viewing the agents' index-page.
OSTicket Version installed: 1.10
Attachment Inline Plugin working like a charme.

Sorry, can't give another information yet.

**Comment by clonemeagain** [comment]
Have you upgraded the attachment plugin recently? It went through a bit of a major overhaul recently, and this plugin got updated to use it's new API.

I should probably update the README's and things when I change API's.. 

Apparently the new code doesn't check to see if it's been upgraded, it just assumes, and you know what they say about assumptions! I'll write a patch.

**Comment by ghost** [comment]
Thank's for your reply.
I tested without your attachement plugin this time and it works. With your attachemnt plugin enabled, your version from Sep 6th is working well.

**Comment by clonemeagain** [comment]
Excellent!
